config/routes.rb
Rails.application.routes.draw do
  resources :uri, id: /.*/,
    format:   false,
    defaults: { format: 'html' },
    only:     %i[index show update edit]

  get 'lists/books_read',    to: 'lists#index_books_read'
  get 'lists/books_to_read', to: 'lists#index_books_to_read'

  get ':year',        to: 'timeline#show_year', constraints: { year: /\d{4}/ }
  get ':year/W:week', to: 'timeline#show_week', constraints: { year: /\d{4}/, week: /\d{1,2}/ }
  get ':year/:month', to: 'timeline#show_month', constraints: { year: /\d{4}/, month: /\d{1,22}/ }
  get ':year/:month/:day', to: 'timeline#show_day', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

#  get ':year', to: 'timeline#index'

  # resources :tags
  resources :wiki, id: /.*/
  # resources :$year/misc/books_read
  # resources :$year/

#  get 'uri_margins/:id', to: 'uri_margins#show', id: /.*/

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/controllers/uri_controller.rb
require 'csv'

class URIController < ApplicationController
  def index
    if params[:uri]
      redirect_to(uri_path(params[:uri]))
      return
    end

    # TODO try looking up the date based upon the sha
    @urls = URIDataService.new.search
  end

  def show
    @title      = params[:title]
    @href       = uri
    @tags       = []
    @tag_source = ''

    if tag_pathname&.exist?
      @tag_year   = tag_pathname.to_s.match(/dated\/([0-9]{4})\//)[1]

      @tag_source = tag_pathname.read
      tags_table = CSV.table(tag_pathname, col_sep: "\t").to_a
      @href  = Addressable::URI.parse(tags_table.find { |x| x.first == 'href' }.last)
      @title = tags_table.find { |x| x.first == 'title' }&.last
      @tags  = tags_table.reject { |x| x.first == :tag || x.first == 'href' || x.first == 'title' }

      # TODO: Figure how the right way to show this?
      # Maybe move into a seperate object
      # Which will then wrap around the repo AND database.
      uri_margins_pathname = Pathname.new("/home/andrew/aspects/prime/dated/#{@tag_year}/uri_margins")
      @commits = Git.open(uri_margins_pathname.to_s).log.path(@href.to_pathname).all
    end

    @index = ReadSourceService.new(index_markdown_pathname)

    @open_library =
      if @href.isbn?
        begin
          OpenLibraryBook.new(@href.isbn)
        rescue
        end
      end
  end

  def edit
    @href  = uri
    @index = ReadSourceService.new(index_markdown_pathname)
  end

  def update
    to_tsv = CSV.generate(col_sep: "\t") do |csv|
      csv << %w[Tag Value]
      csv << [:href, uri]
      csv << [:title, params[:title]] if params[:title].present?
      params[:key].each_index do |i|
        key   = params[:key][i]
        value = params[:value][i]

        if key.present?
          if value.present?
            csv << [key, value]
          else
            csv << [key]
          end
        end
      end
    end

    git = Git.open(repo_pathname)

    # Write tags
    writeable_tag_pathname = tag_pathnames.first

    writeable_tag_pathname.dirname.mkpath
    writeable_tag_pathname.write(to_tsv)

    begin
      git.add(writeable_tag_pathname)
      git.commit_all("Tag #{uri}")
    rescue Git::GitExecuteError
      # Nothing to do, continue with the rest of the sync.
    end

    # Write index
    writeable_index_markdown_pathname = index_markdown_pathnames.first
    if params[:index_markdown].present?
      writeable_index_markdown_pathname.write(
        params[:index_markdown] + "\n"
      )
    else
      writeable_index_markdown_pathname.delete if writeable_index_markdown_pathname.exist?
    end

    begin
      git.add(writeable_index_markdown_pathname)
      git.commit_all("Notes for #{uri}")
    rescue Git::GitExecuteError
      # Nothing to do, continue with the rest of the sync.
    end

    # Sync the commits
    begin
      git.pull('origin')
      git.push('origin')
    rescue Git::GitExecuteError
    end

    # TODO: actually should just re-render the page
    redirect_to(uri_path(uri))
  end

################################################################################

  private

  def index_repo_pathnames
    @index_repo_pathnames ||= repo_pathnames[0, 2]
  end

  def repo_pathnames
    @repo_pathnames ||=
      Pathname.new('/home/andrew/aspects/prime/dated/')
      .children
      .sort.reverse.map { |x| x.join('uri_margins') }.select(&:exist?)
  end

  def repo_pathname
    @repo_pathname ||=
      Pathname.new("/home/andrew/aspects/prime/dated/#{Time.current.year}/uri_margins")
  end

  def uri
    @uri ||= Addressable::URI.parse(params[:id].sub(%r{:/+([^/])}, '://\1'))
  end

  def uri_pathnames
    @uri_pathnames ||= repo_pathnames.map { |x| x + uri.to_pathname }
  end

  def tag_pathnames
    @tag_pathnames ||= uri_pathnames.map { |x| x + 'tags.tsv' }
  end

  def index_markdown_pathnames
    @index_markdown_pathnames ||= uri_pathnames.map { |x| x + 'index.markdown' }
  end

  def tag_pathname
    @tag_pathname ||= tag_pathnames.find { |x| x.exist? }
  end

  def index_markdown_pathname
    @index_markdown_pathname ||=
      index_markdown_pathnames.find { |x| x.exist? }
  end
end

app/views/uri/_tag_form.html.erb
      <div class="nested-form-wrapper" data-new-record="true">
        <%= f.label :description %>
        <%= f.text_field :description %>

        <button type="button" data-action="nested-form#remove">Remove todo</button>

        <%= f.hidden_field :_destroy %>
      </div>

app/views/uri/edit.html.erb
<%= form_with(method: :patch, data: { controller: 'uri-margin' }) do |form| %>
  <%= turbo_frame_tag(:uri_index) do %>
    <div>
      <%= form.submit('Save') %>
      <%= link_to("Cancel", uri_path(@href)) %>
    </div>
    <div>
      <%= @index.content_type %>
    </div>
    <div>
      <%= form.text_area(:index_markdown, value: @index.source, cols: 80, rows: 30) %>
    </div>
    <div>
      <%= form.submit('Save') %>
      <%= link_to("Cancel", uri_path(@href)) %>
    </div>
  <% end %>
<% end %>

app/views/uri/index.html.erb
<h1>URI</h1>

<p>URI Count: <%= @urls.count %></p>
<ul>
<% @urls.sort.each do |href, data| %>
  <li>
    <%= link_to(href, uri_path(href)) %>, <%= data[:date] %>
  </li>

<% end %>
</ul>

app/views/uri/show.html.erb
<h1>
  <ol>
    <li><%= link_to('URI/URL', uri_index_path) %></li>
    <li><%= link_to(html_escape(@href), uri_path(@href)) %></li>
  </ol>
</h1>
<section>
  <dl>
    <dt>URI:</dt>
    <dd><%= link_to(html_escape(@href), @href.to_s) %></dd>

    <%= form_with(method: :patch, data: { controller: 'uri-margin' }) do |form| %>
      <dt>Title:</dt>
      <dd>
        <td><%= form.text_field(:title, value: html_escape(@title)) %></td>
      </dd>

      <dt>Tag Year:</dt>
      <dd><%= @tag_year %></dd>
      <dt>Tags:</dt>
      <dd>
        <table>
          <thead>
            <tr>
              <th>Key</th>
              <th>Value</th>
              <th></th>
            </tr>
          </thead>
          <tbody data-uri-margin-target="tbody">
            <% @tags.each do |tag| %>
              <tr>
                <td><%= form.text_field(
                  :'key[]',
                  value:    html_escape(tag.first),
                  autofill: false,
                  data:     {
                    'uri-margin-target': 'key'
                  }
                ) %></td>
                <td><%= form.text_field(
                  :'value[]',
                  value:    html_escape(tag.last),
                  autofill: false
                ) %></td>
                <td><%= form.button(
                  'X',
                  type:     :button,
                  tabindex: -1,
                  data:     { action: 'click->uri-margin#delete' }
                ) %></td>
              </tr>
            <% end %>
            <tr>
              <td><%= form.text_field(
                :'key[]',
                autofocus: true,
                autofill:  false,
                data:      {
                  action:              'keydown.enter->uri-margin#add:prevent',
                  'uri-margin-target': 'key'
                }
              ) %></td>
              <td><%= form.text_field(
                :'value[]',
                autofill: false,
                data:     { action: 'keydown.enter->uri-margin#add:prevent' }
              ) %></td>
              <td><%= form.button(
                'X',
                type:     :button,
                tabindex: -1,
                data:     { action: 'click->uri-margin#delete' }
              ) %></td>
            </tr>
            <template data-uri-margin-target="template">
              <tr>
                <td><%= form.text_field(
                  :'key[]',
                  tabindex: 0,
                  autofocus: true,
                  autofill:  false,
                  data:      {
                    action:              'keydown.enter->uri-margin#add:prevent',
                    'uri-margin-target': 'key'
                  }
                ) %></td>
                <td><%= form.text_field(
                  :'value[]',
                  autofill: false,
                  data:     { action: 'keydown.enter->uri-margin#add:prevent' }
                ) %></td>
                <td><%= form.button('X', type: :button, data: { action: 'click->uri-margin#delete' }, tabindex: -1) %></td>
              </tr>
            </template>
          </tbody>
          <tfoot>
            <tr>
              <td colspan="3">
                <%= form.button(
                  '+',
                  type:     :button,
                  tabindex: -1,
                  data:     { action: 'click->uri-margin#add' }
                ) %>
              </td>
            </tr>
            <tr>
              <td colspan="3">
                <%= form.submit('Save tags') %>
              </td>
            </tr>
          </tfoot>
        </table>
      </dd>
      <dt>Index</dt>
      <dd>
        <%= turbo_frame_tag(:uri_index) do %>
          <%= link_to('Edit', edit_uri_path(@href)) %>
          <!-- <%= form.text_area(:index_markdown, value: @index_markdown_source, cols: 80, rows: 30) %> -->
          <section>
            <%= @index.html %>
          </section>
        <% end %>
      </dd>
      <!-- <%= form.submit('Save tags') %> -->
    <% end %>
    <dt>Commits</td>
    <dd>
      <ol>
        <% @commits&.each do |commit| %>
          <li><%= commit.author_date %></li>
        <% end %>
      </ol>
    </dd>

  </dl>
</section>

<section>
  <details>
    <summary>Raw</summary>
    <dl>
      <dt>URI Pathname:</dt>
      <dd>
        <ul>
          <% @uri_pathnames.each do |uri_pathname| %>
            <li><%= html_escape(uri_pathname) %></li>
          <% end %>
        </ul>
      </dd>

      <dt>Tag Pathname:</dt>
      <dd><%= html_escape(@tag_pathname) %></dd>

      <dt>Tag Source:</dt>
      <dd><pre><%= html_escape(@tag_source) %></pre></dd>

      <dt>Index Pathname:</dt>
      <dd><%= html_escape(@index_markdown_pathname) %></dt>

      <dt>Index Source:</dt>
      <dd><pre><%= html_escape(@index_markdown_source) %></pre></dd>
    </dl>
  </details>
</section>

<% if @open_library %>
  <section>
    <h2>OpenLibrary</h2>
    <pre><%= JSON.pretty_generate(@open_library.data) %></pre>
  </section>
<% end %>