config/routes.rb
Rails.application.routes.draw do
  resources :uri, id: /.*/,
    format:   false,
    defaults: { format: 'html' },
    only:     %i[index show update edit]

  get 'lists/books_read',    to: 'lists#index_books_read'
  get 'lists/books_to_read', to: 'lists#index_books_to_read'

  get ':year',        to: 'timeline#show_year', constraints: { year: /\d{4}/ }
  get ':year/W:week', to: 'timeline#show_week', constraints: { year: /\d{4}/, week: /\d{1,2}/ }
  get ':year/:month', to: 'timeline#show_month', constraints: { year: /\d{4}/, month: /\d{1,22}/ }
  get ':year/:month/:day', to: 'timeline#show_day', constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{1,2}/ }

#  get ':year', to: 'timeline#index'

  # resources :tags
  resources :wiki, id: /.*/
  # resources :$year/misc/books_read
  # resources :$year/

#  get 'uri_margins/:id', to: 'uri_margins#show', id: /.*/

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cyberpomp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    -->

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- <main class="container mx-auto mt-28 px-5 flex"> -->
    <nav>
      <ul>
        <li><%= link_to('Home', root_path) %></li>
        <li><%= link_to('Wiki', wiki_index_path) %></li>
        <li>
          <%= link_to('URI', uri_index_path) %>
          (
            <%= link_to(
                'bookmarklet',
                "javascript:(function() { window.location.href = `#{uri_index_url}/${encodeURIComponent(window.location.href)}?title=${encodeURIComponent(document.title)}`;})();",
                title: 'URI Bookmarklet'
            ) %>
          )
          <%= form_with(action: uri_index_path, method: :get) do |form| %>
            <%= form.text_field(:uri) %>
            <%= form.submit('Go') %>
          <% end %>
        </li>
      </ul>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>